from django.urls import path

from . import views


urlpatterns = [
    path(
        "health/",
        views.health,
        name="health",
    ),
    path(
        "settings/openai/",
        views.openai_status,
        name="openai-status",
    ),
    path(
        "settings/openai/save/",
        views.openai_save,
        name="openai-save",
    ),
    path(
        "settings/openai/test/",
        views.openai_test,
        name="openai-test",
    ),
    path(
        "missions/create/",
        views.mission_create,
        name="mission-create",
    ),
    path(
        "internal/notify-update/",
        views.notify_update,
        name="notify-update",
    ),
    path(
        "research/search/",
        views.research_search,
        name="research-search",
    ),
    path(
        "research/mock-call/",
        views.mock_call_compare,
        name="mock-call-compare",
    ),
    path(
        "research/history/",
        views.research_history,
        name="research-history",
    ),
    path(
        "images/analyze/",
        views.image_analyze,
        name="image-analyze",
    ),
    path(
        "training/status/",
        views.training_status_view,
        name="training-status",
    ),
    path(
        "training/generate/",
        views.training_generate,
        name="training-generate",
    ),
    path(
        "training/run-auto/",
        views.training_run_auto,
        name="training-run-auto",
    ),
    path(
        "training/feedback/",
        views.training_feedback,
        name="training-feedback",
    ),
    path(
        "notifications/register/",
        views.notification_register,
        name="notification-register",
    ),
    path(
        "live/session/",
        views.live_session_create,
        name="live-session-create",
    ),
    path(
        "voice/status/",
        views.voice_status,
        name="voice-status",
    ),
    path(
        "voice/test-call/",
        views.voice_test_call,
        name="voice-test-call",
    ),
    path(
        "voice/answer/",
        views.voice_answer,
        name="voice-answer",
    ),
    path(
        "voice/respond/",
        views.voice_respond,
        name="voice-respond",
    ),
]
